version: '3'
services:
  
  myrtle:
    container_name: myrtle
    image: myrtle
    build: ./
    ports:
      - 8000:8000
    labels:
      caddy: "{{ domain }}"
      caddy.reverse_proxy: "{{upstreams 8000}}"
    networks:
      - caddy

networks:
  caddy:
    external: true

